name: Environment Variables in workflow

on: push

env:
  VARIABLE: Hello, World!
jobs:
  Example:
    runs-on: ubuntu-latest

    steps:
      - name: Echo environment variables
        run: echo ${{ env.VARIABLE }}
