name: Environment Variables Set or Update

on: push

jobs:
  Example1:
    runs-on: ubuntu-latest

    steps:
      - name: Set environment variables
        run: |
          echo "VARIABLE=Hello, World! (1)" >> $GITHUB_ENV
          echo "VARIABLE=$VARIABLE"
          echo "VARIABLE=${{ env.VARIABLE }}"

      - run: |
          echo "VARIABLE=$VARIABLE"
          echo "VARIABLE=${{ env.VARIABLE }}"

      - name: Update environment variables
        run: |
          echo "VARIABLE=Hello, World! (2)" >> $GITHUB_ENV
          echo "VARIABLE=$VARIABLE"
          echo "VARIABLE=${{ env.VARIABLE }}"

      - run: |
          echo "VARIABLE=$VARIABLE"
          echo "VARIABLE=${{ env.VARIABLE }}"

  Example2:
    runs-on: ubuntu-latest
    needs: Example1    

    steps:
      - run: |
          echo "VARIABLE=$VARIABLE"
          echo "VARIABLE=${{ env.VARIABLE }}"
