name: Environment Variables

on: push

env:
  DRAGON: I am DRAGON

jobs:
  Example1:
    runs-on: ubuntu-latest
    env:
      OGRE: I am OGRE
    
    steps:
      - name: Echo environment variables 1
        env:
          WITCH: I am WITCH
        run: |
          echo "DRAGON=$DRAGON"
          echo "DRAGON=${{ env.DRAGON }}"
          echo "OGRE=$OGRE"
          echo "OGRE=${{ env.OGRE }}"
          echo "WITCH=$WITCH"
          echo "WITCH=${{ env.WITCH }}"

      - name: Echo environment variables 2
        run: |
          echo "DRAGON=$DRAGON"
          echo "DRAGON=${{ env.DRAGON }}"
          echo "OGRE=$OGRE"
          echo "OGRE=${{ env.OGRE }}"
          echo "WITCH=$WITCH"
          echo "WITCH=${{ env.WITCH }}"

  Example2:
    runs-on: ubuntu-latest
    
    steps:
      - name: Echo environment variables 3
        run: |
          echo "DRAGON=$DRAGON"
          echo "DRAGON=${{ env.DRAGON }}"
          echo "OGRE=$OGRE"
          echo "OGRE=${{ env.OGRE }}"
          echo "WITCH=$WITCH"
          echo "WITCH=${{ env.WITCH }}"
