name: Environment Variables Set or Update

on: push

jobs:
  Example:
    runs-on: ubuntu-latest

    steps:
      - name: Set environment variables
        run: echo "VARIABLE=Hello, World! (1)" >> $GITHUB_ENV

      - run: echo "${{ env.VARIABLE }}"

      - name: Update environment variables
        run: echo "VARIABLE=Hello, World! (2)" >> $GITHUB_ENV

      - run: echo "${{ env.VARIABLE }}"