name: Environment Variables in workflow

on: push

env:
  PROLOGUE: A chosen hero embarks on a quest to save a world on the brink of chaos.

jobs:
  Example:
    runs-on: ubuntu-latest

    steps:
      - name: Show prologue
        run: echo ${{ env.PROLOGUE }}
