name: GITHUB_ENV

on: push

jobs:
  Example:
    strategy:
      matrix:
        os: [ ubuntu-latest, windows-latest, macOS-latest ]
    runs-on: ${{ matrix.os }}

    steps:
      - name: Linux or macOS
        if: runner.os != 'Windows'
        run: |
          echo "CI=$CI"
          echo "GITHUB_ACTION=$GITHUB_ACTION"
          echo "GITHUB_ACTION_PATH=$GITHUB_ACTION_PATH"
          echo "GITHUB_ACTION_REPOSITORY=$GITHUB_ACTION_REPOSITORY"
          echo "GITHUB_ACTIONS=$GITHUB_ACTIONS"
          echo "GITHUB_ACTOR=$GITHUB_ACTOR"
          echo "GITHUB_ACTOR_ID=$GITHUB_ACTOR_ID"
          echo "GITHUB_API_URL=$GITHUB_API_URL"
          echo "GITHUB_BASE_REF=$GITHUB_BASE_REF"
          echo "GITHUB_ENV=$GITHUB_ENV"
          echo "GITHUB_EVENT_NAME=$GITHUB_EVENT_NAME"
          echo "GITHUB_EVENT_PATH=$GITHUB_EVENT_PATH"
          echo "GITHUB_GRAPHQL_URL=$GITHUB_GRAPHQL_URL"
          echo "GITHUB_HEAD_REF=$GITHUB_HEAD_REF"
          echo "GITHUB_JOB=$GITHUB_JOB"
          echo "GITHUB_PATH=$GITHUB_PATH"
          echo "GITHUB_REF=$GITHUB_REF"
          echo "GITHUB_REF_NAME=$GITHUB_REF_NAME"
          echo "GITHUB_REF_PROTECTED=$GITHUB_REF_PROTECTED"
          echo "GITHUB_REF_TYPE=$GITHUB_REF_TYPE"
          echo "GITHUB_REPOSITORY=$GITHUB_REPOSITORY"
          echo "GITHUB_REPOSITORY_OWNER=$GITHUB_REPOSITORY_OWNER"
          echo "GITHUB_REPOSITORY_OWNER_ID=$GITHUB_REPOSITORY_OWNER_ID"
          echo "GITHUB_RETENTION_DAYS=$GITHUB_RETENTION_DAYS"
          echo "GITHUB_RUN_ATTEMPT=$GITHUB_RUN_ATTEMPT"
          echo "GITHUB_RUN_ID=$GITHUB_RUN_ID"
          echo "GITHUB_RUN_NUMBER=$GITHUB_RUN_NUMBER"
          echo "GITHUB_SERVER_URL=$GITHUB_SERVER_URL"
          echo "GITHUB_SHA=$GITHUB_SHA"
          echo "GITHUB_STEP_SUMMARY=$GITHUB_STEP_SUMMARY"
          echo "GITHUB_WORKFLOW=$GITHUB_WORKFLOW"
          echo "GITHUB_WORKFLOW_REF=$GITHUB_WORKFLOW_REF"
          echo "GITHUB_WORKFLOW_SHA=$GITHUB_WORKFLOW_SHA"
          echo "GITHUB_WORKSPACE=$GITHUB_WORKSPACE"
          echo "RUNNER_ARCH=$RUNNER_ARCH"
          echo "RUNNER_DEBUG=$RUNNER_DEBUG"
          echo "RUNNER_NAME=$RUNNER_NAME"
          echo "RUNNER_OS=$RUNNER_OS"
          echo "RUNNER_TEMP=$RUNNER_TEMP"
          echo "RUNNER_TOOL_CACHE=$RUNNER_TOOL_CACHE"

      - name: Windows
        if: runner.os == 'Windows'
        run: |
          echo "CI=$env:CI"
          echo "GITHUB_ACTION=$env:GITHUB_ACTION"
          echo "GITHUB_ACTION_PATH=$env:GITHUB_ACTION_PATH"
          echo "GITHUB_ACTION_REPOSITORY=$env:GITHUB_ACTION_REPOSITORY"
          echo "GITHUB_ACTIONS=$env:GITHUB_ACTIONS"
          echo "GITHUB_ACTOR=$env:GITHUB_ACTOR"
          echo "GITHUB_ACTOR_ID=$env:GITHUB_ACTOR_ID"
          echo "GITHUB_API_URL=$env:GITHUB_API_URL"
          echo "GITHUB_BASE_REF=$env:GITHUB_BASE_REF"
          echo "GITHUB_ENV=$env:GITHUB_ENV"
          echo "GITHUB_EVENT_NAME=$env:GITHUB_EVENT_NAME"
          echo "GITHUB_EVENT_PATH=$env:GITHUB_EVENT_PATH"
          echo "GITHUB_GRAPHQL_URL=$env:GITHUB_GRAPHQL_URL"
          echo "GITHUB_HEAD_REF=$env:GITHUB_HEAD_REF"
          echo "GITHUB_JOB=$env:GITHUB_JOB"
          echo "GITHUB_PATH=$env:GITHUB_PATH"
          echo "GITHUB_REF=$env:GITHUB_REF"
          echo "GITHUB_REF_NAME=$env:GITHUB_REF_NAME"
          echo "GITHUB_REF_PROTECTED=$env:GITHUB_REF_PROTECTED"
          echo "GITHUB_REF_TYPE=$env:GITHUB_REF_TYPE"
          echo "GITHUB_REPOSITORY=$env:GITHUB_REPOSITORY"
          echo "GITHUB_REPOSITORY_OWNER=$env:GITHUB_REPOSITORY_OWNER"
          echo "GITHUB_REPOSITORY_OWNER_ID=$env:GITHUB_REPOSITORY_OWNER_ID"
          echo "GITHUB_RETENTION_DAYS=$env:GITHUB_RETENTION_DAYS"
          echo "GITHUB_RUN_ATTEMPT=$env:GITHUB_RUN_ATTEMPT"
          echo "GITHUB_RUN_ID=$env:GITHUB_RUN_ID"
          echo "GITHUB_RUN_NUMBER=$env:GITHUB_RUN_NUMBER"
          echo "GITHUB_SERVER_URL=$env:GITHUB_SERVER_URL"
          echo "GITHUB_SHA=$env:GITHUB_SHA"
          echo "GITHUB_STEP_SUMMARY=$env:GITHUB_STEP_SUMMARY"
          echo "GITHUB_WORKFLOW=$env:GITHUB_WORKFLOW"
          echo "GITHUB_WORKFLOW_REF=$env:GITHUB_WORKFLOW_REF"
          echo "GITHUB_WORKFLOW_SHA=$env:GITHUB_WORKFLOW_SHA"
          echo "GITHUB_WORKSPACE=$env:GITHUB_WORKSPACE"
          echo "RUNNER_ARCH=$env:RUNNER_ARCH"
          echo "RUNNER_DEBUG=$env:RUNNER_DEBUG"
          echo "RUNNER_NAME=$env:RUNNER_NAME"
          echo "RUNNER_OS=$env:RUNNER_OS"
          echo "RUNNER_TEMP=$env:RUNNER_TEMP"
          echo "RUNNER_TOOL_CACHE=$env:RUNNER_TOOL_CACHE"
