name: Job always

on: push

jobs:
  JobA:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Job A"
  
  JobB:
    runs-on: ubuntu-latest
    needs: JobA
    if: ${{ always() }}
    steps:
      - run: echo "Job B"
