name: Trigger multiple filters 2

on:
  pull_request:
    branches:
      - main
    types:
      - opened
      - synchronize
    paths:
      - Unity/**

jobs:
  Example:
    runs-on: macos-latest

    steps:
      - run: echo "Multiple conditions were triggered."
