name: Trigger multiple filters 1

on:
  push:
    branches:
      - develop
    paths:
      - Unity/**

jobs:
  Example:
    runs-on: ubuntu-latest

    steps:
      - run: echo "Multiple conditions were triggered."
